# Generated by Django 5.1.1 on 2025-01-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('adharcard', models.CharField(max_length=12, unique=True)),
                ('is_farmer', models.BooleanField(default=False)),
                ('acre_of_land', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kisan_card', models.CharField(blank=True, max_length=16, null=True)),
                ('is_buyer', models.BooleanField(default=False)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('crops', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
